EE_LIB = lwnbdsvr.a
EE_OBJS = lwnbdsvr.o lwnbd.o nbd_protocol.o drivers/hdd_d.o
EE_LIBS = -lc -lps2ips
EE_INCS += -I. -I../../../include/ -include platform-ps2.h -DAPP_NAME=\"lwnbdsvr\"

ifeq ($(DEBUG),1)
EE_CFLAGS += -DDEBUG -DNBD_DEBUG
endif

all: $(EE_LIB)

clean:
	rm -f -r $(EE_OBJS) $(EE_LIB)

rebuild: clean all

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
