/*
 * ee_lib.h
 *
 */

#ifndef PORTS_PLAYSTATION2_EE_EE_LIB_H_
#define PORTS_PLAYSTATION2_EE_EE_LIB_H_

#include <debug.h>
#include <iopcontrol.h>
#include <kernel.h>
#include <loadfile.h>
#include <sbv_patches.h>
#include <sifrpc.h>
#include <string.h>
#include <tamtypes.h>

// This could be generated by macro ...
extern unsigned char poweroff_irx[];
extern unsigned int size_poweroff_irx;

extern unsigned char mcman_irx[];
extern unsigned int size_mcman_irx;

extern unsigned char ps2dev9_irx[];
extern unsigned int size_ps2dev9_irx;

extern unsigned char ps2atad_irx[];
extern unsigned int size_ps2atad_irx;

extern unsigned char usbd_irx[];
extern unsigned int size_usbd_irx;

extern unsigned char usbhdfsd_irx[];
extern unsigned int size_usbhdfsd_irx;

extern unsigned char sio2man_irx[];
extern unsigned int size_sio2man_irx;

extern unsigned char udptty_irx[];
extern unsigned int size_udptty_irx;

extern unsigned int size_ps2ip_irx;
extern unsigned char ps2ip_irx[];

extern unsigned char libsd_irx[];
extern unsigned int size_libsd_irx;

extern unsigned char audsrv_irx[];
extern unsigned int size_audsrv_irx;

extern unsigned char ps2ip_nm_irx[];
extern unsigned int size_ps2ip_nm_irx;

extern unsigned char netman_irx[];
extern unsigned int size_netman_irx;

extern unsigned char smap_irx[];
extern unsigned int size_smap_irx;

int init_platform();
int set_ipconfig();

#endif /* PORTS_PLAYSTATION2_EE_EE_LIB_H_ */
